import {FormEvent, useCallback, useEffect, useRef, useState} from 'react';
import {Bell, BookOpen, Bot, Brain, Camera, CheckSquare, ChevronRight, CircleUserRound, Database, Globe2, Home, Menu, Mic, MicOff, Moon, PanelRightClose, PanelRightOpen, Play, Send, Settings, ShieldCheck, ShieldX, Sparkles, Square, Sun, Trash2, Upload, Users, Volume2, VolumeX, X} from 'lucide-react';

const API='http://127.0.0.1:8000';
type Message={id:string;role:'user'|'assistant'|'status';text:string};
type SystemStatus={status:string;model:string;reasoning:boolean;queue:{active:boolean;waiting:number};speech:{ready:boolean;wake_word:string};camera_monitor:boolean;agents:{id:string;name:string;status:string}[];database:string;rag:{ready:boolean;documents:number;model:string}};
type Approval={kind:'agent'|'codex'|'curator';id:string;title:string;body:string};
type AgentTask={id:string;agent:string;status:string;summary:string;error_type?:string;error_summary?:string;result_summary?:string};
type KnowledgeDoc={id:string;title:string;filename:string;scope:string;chunks:number;created_at:string};
const id=()=>crypto.randomUUID();

function App(){
  const [messages,setMessages]=useState<Message[]>([{id:id(),role:'assistant',text:'Good evening, *. I’m ready when you are.'}]);
  const [activeSection,setActiveSection]=useState('Home');
  const [input,setInput]=useState(''); const [busy,setBusy]=useState(false); const [activity,setActivity]=useState('Ready');
  const [stopped,setStopped]=useState(false); const [lastQuestion,setLastQuestion]=useState(''); const requestController=useRef<AbortController|null>(null);
  const [status,setStatus]=useState<SystemStatus|null>(null); const [rightOpen,setRightOpen]=useState(true); const [mobileNav,setMobileNav]=useState(false);
  const [dark,setDark]=useState(localStorage.getItem('family-theme')==='dark'); const [autoSpeak,setAutoSpeak]=useState(localStorage.getItem('family-auto-speak-v2')==='true');
  const [listening,setListening]=useState(false); const [voiceHint,setVoiceHint]=useState('Starting hands-free listening…');
  const [approvals,setApprovals]=useState<Approval[]>([]); const [approvalOpen,setApprovalOpen]=useState(false); const [deciding,setDeciding]=useState<string|null>(null);
  const [knowledge,setKnowledge]=useState<KnowledgeDoc[]>([]); const [knowledgeOpen,setKnowledgeOpen]=useState(false); const [uploading,setUploading]=useState(false); const fileInput=useRef<HTMLInputElement|null>(null);
  const endRef=useRef<HTMLDivElement>(null); const audioRef=useRef<HTMLAudioElement|null>(null);
  const autoSpeakRef=useRef(autoSpeak);
  const playbackId=useRef(0);
  const wakeArmedUntil=useRef(0);
  const recorder=useRef<{stream:MediaStream;context:AudioContext;processor:ScriptProcessorNode}|null>(null);
  const voiceState=useRef({speaking:false,parts:[] as Float32Array[],pre:[] as Float32Array[],silence:0,voice:0,transcribing:false,paused:false,noise:.004});
  useEffect(()=>{document.documentElement.dataset.theme=dark?'dark':'light';localStorage.setItem('family-theme',dark?'dark':'light')},[dark]);
  useEffect(()=>{autoSpeakRef.current=autoSpeak;localStorage.setItem('family-auto-speak-v2',String(autoSpeak))},[autoSpeak]);
  useEffect(()=>endRef.current?.scrollIntoView({behavior:'smooth'}),[messages,activity]);

  const refreshStatus=useCallback(async()=>{try{const r=await fetch(`${API}/api/system/status`);if(r.ok)setStatus(await r.json())}catch{setStatus(null)}},[]);
  useEffect(()=>{refreshStatus();const timer=setInterval(refreshStatus,3000);return()=>clearInterval(timer)},[refreshStatus]);
  const refreshApprovals=useCallback(async()=>{try{const r=await fetch(`${API}/api/approvals?member_id=*`);if(r.ok)setApprovals((await r.json()).items||[])}catch{}},[]);
  useEffect(()=>{void refreshApprovals();const timer=setInterval(()=>void refreshApprovals(),15000);return()=>clearInterval(timer)},[refreshApprovals]);
  const watchCodexTask=useCallback(async(taskId:string)=>{const messageId=`codex-${taskId}`;setApprovalOpen(false);setMessages(m=>[...m,{id:messageId,role:'status',text:`Codex is running…\nTask · ${taskId.slice(0,8)}`}]);for(let attempt=0;attempt<900;attempt++){try{const r=await fetch(`${API}/api/tasks/${taskId}?member_id=*`);if(r.ok){const task=await r.json() as AgentTask;if(task.status==='completed'){const output=task.result_summary?.trim()||'Codex completed without text output.';setMessages(m=>[...m.filter(x=>x.id!==messageId),{id:id(),role:'assistant',text:`Codex output:\n\n${output}`}]);return}if(task.status==='failed'){setMessages(m=>[...m.filter(x=>x.id!==messageId),{id:id(),role:'assistant',text:`Codex failed: ${task.error_type||'Error'}${task.error_summary?` — ${task.error_summary}`:''}`}]);return}setMessages(m=>m.map(x=>x.id===messageId?{...x,text:`Codex is ${task.status}…\nTask · ${taskId.slice(0,8)}`} : x))}}catch{}await new Promise(resolve=>setTimeout(resolve,2000))}setMessages(m=>m.map(x=>x.id===messageId?{...x,text:`Codex is still running. Task · ${taskId.slice(0,8)}`} : x))},[]);
  const decideApproval=async(item:Approval,decision:'approve'|'deny')=>{setDeciding(item.id);try{const r=await fetch(`${API}/api/approvals/${item.kind}/${item.id}/${decision}?member_id=*`,{method:'POST'});if(!r.ok)throw Error();setApprovals(x=>x.filter(a=>a.id!==item.id));if(item.kind==='codex'&&decision==='approve'){void watchCodexTask(item.id)}else setMessages(m=>[...m,{id:id(),role:'assistant',text:decision==='approve'?`Approved: ${item.title}. The scoped operation will continue.`:`Denied: ${item.title}. Nothing will be executed.`}])}catch{await refreshApprovals()}finally{setDeciding(null)}};
  const refreshKnowledge=async()=>{const r=await fetch(`${API}/api/knowledge?member_id=*`);if(r.ok)setKnowledge((await r.json()).items||[])};
  const uploadKnowledge=async(file:File)=>{setUploading(true);setActivity('Indexing knowledge');try{const data=new FormData();data.append('file',file);const r=await fetch(`${API}/api/knowledge/upload?member_id=*&scope=private`,{method:'POST',body:data});if(!r.ok)throw Error(await r.text());const result=await r.json();await refreshKnowledge();setMessages(m=>[...m,{id:id(),role:'assistant',text:`Knowledge indexed: ${result.filename} (${result.chunks} chunks). I can now use it when relevant.`}])}catch(e){setMessages(m=>[...m,{id:id(),role:'assistant',text:`Knowledge import failed: ${String(e)}`}])}finally{setUploading(false);setActivity('Ready')}};
  const deleteKnowledge=async(documentId:string)=>{const r=await fetch(`${API}/api/knowledge/${documentId}?member_id=*`,{method:'DELETE'});if(r.ok)await refreshKnowledge()};

  const speak=useCallback(async(text:string)=>{if(!autoSpeakRef.current)return;const run=++playbackId.current;voiceState.current.paused=true;audioRef.current?.pause();const spoken=text.split(/^\s*(?:#{1,6}\s*)?(?:消息来源|来源(?:标题)?|数据来源|参考资料|sources?|references?)\s*[:：]?/im)[0].trim();const sentences=spoken.split(/(?<=[。！？.!?；;])\s*/).filter(Boolean);const parts:string[]=[];for(const sentence of sentences){const max=/[\u3400-\u9fff]/.test(sentence)?90:220;for(let i=0;i<sentence.length;i+=max)parts.push(sentence.slice(i,i+max))}const resume=()=>{if(run!==playbackId.current)return;audioRef.current=null;const s=voiceState.current;s.speaking=false;s.parts=[];s.pre=[];s.silence=0;s.voice=0;s.paused=false;setVoiceHint('Listening for “*”…');setActivity('Listening for *')};if(!parts.length){resume();return}const fetchPart=async(part:string)=>{const r=await fetch(`${API}/api/speech/synthesize`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({text:part})});if(!r.ok)throw Error(`speech ${r.status}`);return r.blob()};try{setActivity('Generating first sentence');let pending=fetchPart(parts[0]);for(let i=0;i<parts.length&&run===playbackId.current&&autoSpeakRef.current;i++){const blob=await pending;if(run!==playbackId.current)return;if(i+1<parts.length)pending=fetchPart(parts[i+1]);const url=URL.createObjectURL(blob),audio=new Audio(url);audioRef.current=audio;setActivity('Speaking');await new Promise<void>((resolve,reject)=>{audio.onended=()=>{URL.revokeObjectURL(url);resolve()};audio.onerror=()=>{URL.revokeObjectURL(url);reject(Error('audio playback'))};audio.play().catch(reject)})}resume()}catch(e){resume();setVoiceHint(`Speech output failed: ${String(e)}`)}},[]);

  const send=useCallback(async(raw:string)=>{const text=raw.trim();if(!text||busy)return;const controller=new AbortController();requestController.current=controller;setBusy(true);setStopped(false);setLastQuestion(text);setInput('');setMessages(m=>[...m,{id:id(),role:'user',text}]);const sid=id();setMessages(m=>[...m,{id:sid,role:'status',text:'Main Agent is selecting the right tool…'}]);setActivity('Working');try{const r=await fetch(`${API}/api/chat/stream`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({member_id:'*',thread_id:'desktop',message:text}),signal:controller.signal});if(!r.ok)throw Error(`HTTP ${r.status}`);const reader=r.body!.getReader(),decoder=new TextDecoder();let buffer='';while(true){const {value,done}=await reader.read();if(done)break;buffer+=decoder.decode(value,{stream:true});const lines=buffer.split('\n');buffer=lines.pop()||'';for(const line of lines){if(!line)continue;const event=JSON.parse(line);if(event.type==='status'){setActivity(event.message);setMessages(m=>m.map(x=>x.id===sid?{...x,text:event.message}:x))}if(event.type==='answer'){setMessages(m=>[...m.filter(x=>x.id!==sid),{id:id(),role:'assistant',text:event.reply}]);setActivity('Ready');void speak(event.reply)}if(event.type==='error')throw Error(event.message)}}}catch(e){if((e as Error).name==='AbortError'){setMessages(m=>m.map(x=>x.id===sid?{...x,text:'Stopped. Press Continue to resume this request.'}:x));setActivity('Stopped');setStopped(true)}else{setMessages(m=>m.map(x=>x.id===sid?{...x,text:`Connection issue: ${String(e)}`}:x));setActivity('Offline')}}finally{if(requestController.current===controller)requestController.current=null;setBusy(false);refreshStatus()}},[busy,refreshStatus,speak]);
  const stopAgent=()=>{requestController.current?.abort();playbackId.current++;if(audioRef.current){audioRef.current.pause();audioRef.current=null}voiceState.current.paused=false;setStopped(true);setActivity('Stopped')};
  const continueAgent=()=>{if(!busy&&lastQuestion)void send(lastQuestion)};

  const routeTranscript=useCallback(async(blob:Blob)=>{if(voiceState.current.transcribing)return;voiceState.current.transcribing=true;setVoiceHint('Understanding speech…');try{const data=new FormData();data.append('audio',blob,'voice.wav');const tr=await fetch(`${API}/api/speech/transcribe`,{method:'POST',body:data});if(!tr.ok)throw Error(`transcription ${tr.status}`);const {text}=await tr.json();const rr=await fetch(`${API}/api/speech/route`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({transcript:text,follow_up_active:Date.now()<wakeArmedUntil.current})});if(!rr.ok)throw Error(`routing ${rr.status}`);const decision=await rr.json();if(decision.should_respond){wakeArmedUntil.current=0;setVoiceHint(`Heard: ${decision.message}`);void send(decision.message)}else if(decision.reason==='wake_only'){wakeArmedUntil.current=Date.now()+8000;setVoiceHint('* is awake — say your question');const context=recorder.current?.context;if(context){const oscillator=context.createOscillator(),gain=context.createGain();oscillator.frequency.setValueAtTime(660,context.currentTime);oscillator.frequency.exponentialRampToValueAtTime(880,context.currentTime+.12);gain.gain.setValueAtTime(.0001,context.currentTime);gain.gain.exponentialRampToValueAtTime(.12,context.currentTime+.02);gain.gain.exponentialRampToValueAtTime(.0001,context.currentTime+.16);oscillator.connect(gain);gain.connect(context.destination);oscillator.start();oscillator.stop(context.currentTime+.17)}}else setVoiceHint('Listening for “*”…')}catch(e){setVoiceHint(`Voice input retrying: ${String(e)}`)}finally{voiceState.current.transcribing=false}},[send]);

  const wav=(parts:Float32Array[],rate:number)=>{const length=parts.reduce((n,p)=>n+p.length,0),all=new Float32Array(length);let o=0;parts.forEach(p=>{all.set(p,o);o+=p.length});const b=new ArrayBuffer(44+length*2),v=new DataView(b),w=(o:number,s:string)=>[...s].forEach((c,i)=>v.setUint8(o+i,c.charCodeAt(0)));w(0,'RIFF');v.setUint32(4,36+length*2,true);w(8,'WAVE');w(12,'fmt ');v.setUint32(16,16,true);v.setUint16(20,1,true);v.setUint16(22,1,true);v.setUint32(24,rate,true);v.setUint32(28,rate*2,true);v.setUint16(32,2,true);v.setUint16(34,16,true);w(36,'data');v.setUint32(40,length*2,true);all.forEach((x,i)=>v.setInt16(44+i*2,Math.max(-1,Math.min(1,x))*(x<0?32768:32767),true));return new Blob([b],{type:'audio/wav'})};

  const startListening=async()=>{if(recorder.current)return;try{const stream=await navigator.mediaDevices.getUserMedia({audio:{channelCount:1,echoCancellation:true,noiseSuppression:true,autoGainControl:true}});const context=new AudioContext();if(context.state==='suspended')await context.resume();const source=context.createMediaStreamSource(stream),processor=context.createScriptProcessor(4096,1,1),silent=context.createGain();silent.gain.value=0;processor.onaudioprocess=e=>{const s=voiceState.current;if(s.paused||s.transcribing)return;const chunk=new Float32Array(e.inputBuffer.getChannelData(0));let p=0;chunk.forEach(x=>p+=x*x);const rms=Math.sqrt(p/chunk.length),start=Math.max(.008,s.noise*2.4),stop=Math.max(.005,s.noise*1.4);s.pre.push(chunk);if(s.pre.length>10)s.pre.shift();if(!s.speaking){s.noise=s.noise*.96+Math.min(rms,.02)*.04;if(rms>start){s.speaking=true;s.parts=s.pre.slice();s.silence=0;s.voice=1}}else{s.parts.push(chunk);if(rms>start)s.voice++;s.silence=rms<stop?s.silence+1:0;if(s.silence>8||s.parts.length*4096/context.sampleRate>20){const parts=s.parts,valid=s.voice>=2;s.speaking=false;s.parts=[];s.silence=0;s.voice=0;if(valid&&parts.length>6)void routeTranscript(wav(parts,context.sampleRate))}}};source.connect(processor);processor.connect(silent);silent.connect(context.destination);recorder.current={stream,context,processor};setListening(true);setVoiceHint('Listening for “*”…');setActivity('Listening for *')}catch(e){setListening(false);setVoiceHint(`Microphone unavailable — click the microphone to retry: ${String(e)}`);setActivity('Microphone unavailable')}};
  const stopListening=async()=>{const r=recorder.current;if(r){r.processor.disconnect();r.stream.getTracks().forEach(t=>t.stop());await r.context.close()}recorder.current=null;setListening(false);setVoiceHint('Microphone muted — click to resume');setActivity('Microphone muted')};
  const toggleSpeechOutput=()=>{const enabled=!autoSpeak;autoSpeakRef.current=enabled;setAutoSpeak(enabled);if(!enabled){playbackId.current++;audioRef.current?.pause();audioRef.current=null;voiceState.current.paused=false;setVoiceHint('Listening for “*”…');setActivity('Listening for *')}};

  useEffect(()=>()=>{recorder.current?.stream.getTracks().forEach(t=>t.stop());audioRef.current?.pause()},[]);
  const submit=(e:FormEvent)=>{e.preventDefault();void send(input)};
  const openSection=(label:string)=>{setActiveSection(label);setMobileNav(false);if(label==='Family Memory')void send('/memory');else if(label==='Knowledge'){setKnowledgeOpen(true);void refreshKnowledge()}else if(label==='Tasks')void send('/todo list');else if(label==='Agents')void send('/agents');else if(label==='Cameras')setMessages(m=>[...m,{id:id(),role:'assistant',text:'Camera monitoring is shown in System Status. Ask “Describe the current * camera” or “描述当前 * 画面” to inspect a live view.'}]);else if(label==='Financial Studio')setMessages(m=>[...m,{id:id(),role:'assistant',text:'Financial Video Studio workspace is at * Its Agent runs inside Family AI.'}]);else if(label==='Settings')setMessages(m=>[...m,{id:id(),role:'assistant',text:'Appearance, voice, model and privacy settings are being consolidated here. Dark mode and system-panel controls are available in the top-right corner.'}])};
  const nav=[['Home',Home],['Conversations',Bot],['Family Memory',Brain],['Knowledge',BookOpen],['Tasks',CheckSquare],['Cameras',Camera],['Agents',Users],['Financial Studio',Sparkles],['Settings',Settings]] as const;
  return <div className="app-shell">
    <aside className={`sidebar ${mobileNav?'show':''}`}><div className="window-drag"/><div className="brand"><div className="brand-mark">H</div><div><b>Hearth</b><span>Family AI</span></div><button className="mobile-close" onClick={()=>setMobileNav(false)}><X/></button></div>
      <nav>{nav.map(([label,Icon])=><button key={label} className={activeSection===label?'active':''} onClick={()=>openSection(label)}><Icon/><span>{label}</span>{label==='Agents'&&status&&<em>{status.agents.length}</em>}</button>)}</nav>
      <div className="family-card"><CircleUserRound/><div><b>*</b><span>Home member</span></div><ChevronRight/></div>
    </aside>
    <main className="main-panel"><header><button className="icon mobile-menu" onClick={()=>setMobileNav(true)}><Menu/></button><div><h1>Family Assistant</h1><p><i className={status?'online-dot':'offline-dot'}/>{status?'Local system online':'Connecting to local system'}</p></div><div className="header-actions"><button className={`icon approval-bell ${approvals.length?'has-approvals':''}`} title="Approval Center" onClick={()=>{setApprovalOpen(true);void refreshApprovals()}}><Bell/>{approvals.length>0&&<b>{approvals.length}</b>}</button><button className={`icon speech-toggle ${autoSpeak?'active':''}`} title={autoSpeak?'Voice output on — click for text only':'Text only — click to enable voice output'} onClick={toggleSpeechOutput}>{autoSpeak?<Volume2/>:<VolumeX/>}</button><button className="icon" onClick={()=>setDark(!dark)}>{dark?<Sun/>:<Moon/>}</button><button className="icon" onClick={()=>setRightOpen(!rightOpen)}>{rightOpen?<PanelRightClose/>:<PanelRightOpen/>}</button></div></header>
      <section className="conversation"><div className="day-label">TODAY</div>{messages.map(m=><div key={m.id} className={`message-row ${m.role}`}><div className="message-avatar">{m.role==='user'?'A':m.role==='status'?<span className="spinner"/>:'H'}</div><div className="message-body"><span className="author">{m.role==='user'?'You':m.role==='status'?'Working':'Family AI'}</span><div className="bubble">{m.text}</div></div></div>)}<div ref={endRef}/></section>
      <section className="composer-area"><div className={`work-pill ${busy?'active':''}`}><span/>{activity}</div><form onSubmit={submit}><button type="button" title={listening?'Mute microphone':'Resume hands-free listening'} className={`voice-button ${listening?'listening':''}`} onClick={()=>listening?void stopListening():void startListening()}>{listening?<MicOff/>:<Mic/>}</button><textarea value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();void send(input)}}} placeholder="Say “*…” or type a message" rows={1}/>{busy?<button type="button" className="stop-button" title="Stop Agent" onClick={stopAgent}><Square/></button>:stopped&&lastQuestion?<button type="button" className="continue-button" title="Continue last request" onClick={continueAgent}><Play/></button>:<button className="send-button" disabled={!input.trim()}><Send/></button>}</form><div className="composer-meta"><span>{voiceHint}</span><span>{autoSpeak?'Text + voice output':'Text output only'} · Local-first · Private</span></div></section>
    </main>
    <aside className={`status-panel ${rightOpen?'':'closed'}`}><div className="status-title"><span>System status</span><b>{status?'LIVE':'OFFLINE'}</b></div><StatusCard icon={<Brain/>} title="Local model" value={status?.model||'Connecting…'} detail={status?.reasoning?'Deep reasoning enabled':'Unavailable'} good={!!status}/><StatusCard icon={<Mic/>} title="Voice" value={listening?'Listening':'Ready'} detail={`Wake word · ${status?.speech.wake_word||'*'}`} good={!!status?.speech.ready}/><StatusCard icon={<BookOpen/>} title="Knowledge RAG" value={status?.rag?.ready?'Ready':'Unavailable'} detail={`${status?.rag?.documents||0} documents · vector index`} good={!!status?.rag?.ready}/><StatusCard icon={<Camera/>} title="Cameras" value={status?.camera_monitor?'Monitoring':'Unavailable'} detail="*" good={!!status?.camera_monitor}/><StatusCard icon={<Database/>} title="Memory" value={status?.database==='postgresql'?'PostgreSQL':status?.database==='postgresql-offline'?'PostgreSQL offline':'Local database'} detail="Private family context" good={status?.database==='postgresql'||status?.database==='sqlite'}/><div className="agent-list"><div className="section-label">AGENTS</div>{status?.agents.map(a=><div className={`agent ${a.status}`} key={a.id}><span>{a.name[0]}</span><div><b>{a.name.replace(' Agent','')}</b><small>{a.status==='active'?'Working':'Ready'}</small></div><i/></div>)}</div><div className="queue"><Globe2/><div><b>{status?.queue.active?'Model is working':'Queue is clear'}</b><span>{status?.queue.waiting||0} waiting</span></div></div></aside>
    {approvalOpen&&<div className="approval-overlay" onMouseDown={e=>{if(e.target===e.currentTarget)setApprovalOpen(false)}}><section className="approval-center"><div className="approval-head"><div><span>SECURE ACTIONS</span><h2>Approval Center</h2><p>Nothing continues without your decision.</p></div><button className="icon" onClick={()=>setApprovalOpen(false)}><X/></button></div><div className="approval-list">{approvals.length===0?<div className="approval-empty"><ShieldCheck/><h3>You're all caught up</h3><p>There are no requests waiting for approval.</p></div>:approvals.map(item=><article className="approval-item" key={item.id}><div className="approval-type">{item.kind==='codex'?'CODEX':item.kind==='agent'?'AGENT':'UPGRADE'}</div><h3>{item.title}</h3><p>{item.body}</p><small>Request · {item.id.slice(0,8)}</small><div className="approval-actions"><button className="deny" disabled={deciding===item.id} onClick={()=>void decideApproval(item,'deny')}><ShieldX/>Deny</button><button className="approve" disabled={deciding===item.id} onClick={()=>void decideApproval(item,'approve')}><ShieldCheck/>{deciding===item.id?'Processing…':'Approve'}</button></div></article>)}</div></section></div>}
    {knowledgeOpen&&<div className="approval-overlay" onMouseDown={e=>{if(e.target===e.currentTarget)setKnowledgeOpen(false)}}><section className="approval-center"><div className="approval-head"><div><span>PRIVATE RAG</span><h2>Family Knowledge</h2><p>Upload documents for local retrieval. Nothing is sent to the cloud.</p></div><button className="icon" onClick={()=>setKnowledgeOpen(false)}><X/></button></div><div className="knowledge-tools"><input ref={fileInput} hidden type="file" accept=".pdf,.txt,.md,.markdown,.csv,.json,.html,.htm" onChange={e=>{const file=e.target.files?.[0];if(file)void uploadKnowledge(file);e.currentTarget.value=''}}/><button disabled={uploading} onClick={()=>fileInput.current?.click()}><Upload/>{uploading?'Indexing…':'Add document'}</button></div><div className="approval-list">{knowledge.length===0?<div className="approval-empty"><BookOpen/><h3>No documents yet</h3><p>Add a PDF or text document, then ask questions naturally.</p></div>:knowledge.map(doc=><article className="knowledge-item" key={doc.id}><BookOpen/><div><h3>{doc.title}</h3><p>{doc.filename} · {doc.chunks} chunks · {doc.scope}</p></div><button title="Delete document" onClick={()=>void deleteKnowledge(doc.id)}><Trash2/></button></article>)}</div></section></div>}
  </div>
}

function StatusCard({icon,title,value,detail,good}:{icon:React.ReactNode;title:string;value:string;detail:string;good:boolean}){return <div className="status-card"><div className="status-icon">{icon}</div><div><span>{title}</span><b>{value}</b><small>{detail}</small></div><i className={good?'good':''}/></div>}
export default App;
